// Code generated by go-swagger; DO NOT EDIT.

package student

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AddStudentReader is a Reader for the AddStudent structure.
type AddStudentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddStudentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddStudentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 405:
		result := NewAddStudentMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewAddStudentConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddStudentOK creates a AddStudentOK with default headers values
func NewAddStudentOK() *AddStudentOK {
	return &AddStudentOK{}
}

/* AddStudentOK describes a response with status code 200, with default header values.

Success
*/
type AddStudentOK struct {
}

func (o *AddStudentOK) Error() string {
	return fmt.Sprintf("[POST /student][%d] addStudentOK ", 200)
}

func (o *AddStudentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddStudentMethodNotAllowed creates a AddStudentMethodNotAllowed with default headers values
func NewAddStudentMethodNotAllowed() *AddStudentMethodNotAllowed {
	return &AddStudentMethodNotAllowed{}
}

/* AddStudentMethodNotAllowed describes a response with status code 405, with default header values.

Invalid input
*/
type AddStudentMethodNotAllowed struct {
}

func (o *AddStudentMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /student][%d] addStudentMethodNotAllowed ", 405)
}

func (o *AddStudentMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddStudentConflict creates a AddStudentConflict with default headers values
func NewAddStudentConflict() *AddStudentConflict {
	return &AddStudentConflict{}
}

/* AddStudentConflict describes a response with status code 409, with default header values.

Already exists
*/
type AddStudentConflict struct {
}

func (o *AddStudentConflict) Error() string {
	return fmt.Sprintf("[POST /student][%d] addStudentConflict ", 409)
}

func (o *AddStudentConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
