// Code generated by go-swagger; DO NOT EDIT.

package student

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteStudentReader is a Reader for the DeleteStudent structure.
type DeleteStudentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteStudentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 400:
		result := NewDeleteStudentBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteStudentNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteStudentBadRequest creates a DeleteStudentBadRequest with default headers values
func NewDeleteStudentBadRequest() *DeleteStudentBadRequest {
	return &DeleteStudentBadRequest{}
}

/* DeleteStudentBadRequest describes a response with status code 400, with default header values.

Invalid ID supplied
*/
type DeleteStudentBadRequest struct {
}

func (o *DeleteStudentBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /student/{studentId}][%d] deleteStudentBadRequest ", 400)
}

func (o *DeleteStudentBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteStudentNotFound creates a DeleteStudentNotFound with default headers values
func NewDeleteStudentNotFound() *DeleteStudentNotFound {
	return &DeleteStudentNotFound{}
}

/* DeleteStudentNotFound describes a response with status code 404, with default header values.

Student not found
*/
type DeleteStudentNotFound struct {
}

func (o *DeleteStudentNotFound) Error() string {
	return fmt.Sprintf("[DELETE /student/{studentId}][%d] deleteStudentNotFound ", 404)
}

func (o *DeleteStudentNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
