// Code generated by go-swagger; DO NOT EDIT.

package student

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/restclient/models"
)

// FindStudentByStatusReader is a Reader for the FindStudentByStatus structure.
type FindStudentByStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindStudentByStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindStudentByStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewFindStudentByStatusBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewFindStudentByStatusOK creates a FindStudentByStatusOK with default headers values
func NewFindStudentByStatusOK() *FindStudentByStatusOK {
	return &FindStudentByStatusOK{}
}

/* FindStudentByStatusOK describes a response with status code 200, with default header values.

Success
*/
type FindStudentByStatusOK struct {
	Payload []*models.Student
}

func (o *FindStudentByStatusOK) Error() string {
	return fmt.Sprintf("[GET /student/findByStatus][%d] findStudentByStatusOK  %+v", 200, o.Payload)
}
func (o *FindStudentByStatusOK) GetPayload() []*models.Student {
	return o.Payload
}

func (o *FindStudentByStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindStudentByStatusBadRequest creates a FindStudentByStatusBadRequest with default headers values
func NewFindStudentByStatusBadRequest() *FindStudentByStatusBadRequest {
	return &FindStudentByStatusBadRequest{}
}

/* FindStudentByStatusBadRequest describes a response with status code 400, with default header values.

Invalid status value
*/
type FindStudentByStatusBadRequest struct {
}

func (o *FindStudentByStatusBadRequest) Error() string {
	return fmt.Sprintf("[GET /student/findByStatus][%d] findStudentByStatusBadRequest ", 400)
}

func (o *FindStudentByStatusBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
