// Code generated by go-swagger; DO NOT EDIT.

package student

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/restclient/models"
)

// GetStudentByIDReader is a Reader for the GetStudentByID structure.
type GetStudentByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStudentByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStudentByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetStudentByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetStudentByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetStudentByIDOK creates a GetStudentByIDOK with default headers values
func NewGetStudentByIDOK() *GetStudentByIDOK {
	return &GetStudentByIDOK{}
}

/* GetStudentByIDOK describes a response with status code 200, with default header values.

successful operation
*/
type GetStudentByIDOK struct {
	Payload *models.Student
}

func (o *GetStudentByIDOK) Error() string {
	return fmt.Sprintf("[GET /student/{studentId}][%d] getStudentByIdOK  %+v", 200, o.Payload)
}
func (o *GetStudentByIDOK) GetPayload() *models.Student {
	return o.Payload
}

func (o *GetStudentByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Student)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStudentByIDBadRequest creates a GetStudentByIDBadRequest with default headers values
func NewGetStudentByIDBadRequest() *GetStudentByIDBadRequest {
	return &GetStudentByIDBadRequest{}
}

/* GetStudentByIDBadRequest describes a response with status code 400, with default header values.

Invalid ID supplied
*/
type GetStudentByIDBadRequest struct {
}

func (o *GetStudentByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /student/{studentId}][%d] getStudentByIdBadRequest ", 400)
}

func (o *GetStudentByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetStudentByIDNotFound creates a GetStudentByIDNotFound with default headers values
func NewGetStudentByIDNotFound() *GetStudentByIDNotFound {
	return &GetStudentByIDNotFound{}
}

/* GetStudentByIDNotFound describes a response with status code 404, with default header values.

Student not found
*/
type GetStudentByIDNotFound struct {
}

func (o *GetStudentByIDNotFound) Error() string {
	return fmt.Sprintf("[GET /student/{studentId}][%d] getStudentByIdNotFound ", 404)
}

func (o *GetStudentByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
