// Code generated by go-swagger; DO NOT EDIT.

package student

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"example.com/restclient/models"
)

// NewUpdateStudentParams creates a new UpdateStudentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateStudentParams() *UpdateStudentParams {
	return &UpdateStudentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateStudentParamsWithTimeout creates a new UpdateStudentParams object
// with the ability to set a timeout on a request.
func NewUpdateStudentParamsWithTimeout(timeout time.Duration) *UpdateStudentParams {
	return &UpdateStudentParams{
		timeout: timeout,
	}
}

// NewUpdateStudentParamsWithContext creates a new UpdateStudentParams object
// with the ability to set a context for a request.
func NewUpdateStudentParamsWithContext(ctx context.Context) *UpdateStudentParams {
	return &UpdateStudentParams{
		Context: ctx,
	}
}

// NewUpdateStudentParamsWithHTTPClient creates a new UpdateStudentParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateStudentParamsWithHTTPClient(client *http.Client) *UpdateStudentParams {
	return &UpdateStudentParams{
		HTTPClient: client,
	}
}

/* UpdateStudentParams contains all the parameters to send to the API endpoint
   for the update student operation.

   Typically these are written to a http.Request.
*/
type UpdateStudentParams struct {

	/* Body.

	   Student to be updated
	*/
	Body *models.Student

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update student params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateStudentParams) WithDefaults() *UpdateStudentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update student params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateStudentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update student params
func (o *UpdateStudentParams) WithTimeout(timeout time.Duration) *UpdateStudentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update student params
func (o *UpdateStudentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update student params
func (o *UpdateStudentParams) WithContext(ctx context.Context) *UpdateStudentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update student params
func (o *UpdateStudentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update student params
func (o *UpdateStudentParams) WithHTTPClient(client *http.Client) *UpdateStudentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update student params
func (o *UpdateStudentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update student params
func (o *UpdateStudentParams) WithBody(body *models.Student) *UpdateStudentParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update student params
func (o *UpdateStudentParams) SetBody(body *models.Student) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateStudentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
