// Code generated by go-swagger; DO NOT EDIT.

package student

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateStudentReader is a Reader for the UpdateStudent structure.
type UpdateStudentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateStudentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateStudentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateStudentBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateStudentNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewUpdateStudentMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateStudentOK creates a UpdateStudentOK with default headers values
func NewUpdateStudentOK() *UpdateStudentOK {
	return &UpdateStudentOK{}
}

/* UpdateStudentOK describes a response with status code 200, with default header values.

Success
*/
type UpdateStudentOK struct {
}

func (o *UpdateStudentOK) Error() string {
	return fmt.Sprintf("[PUT /student][%d] updateStudentOK ", 200)
}

func (o *UpdateStudentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateStudentBadRequest creates a UpdateStudentBadRequest with default headers values
func NewUpdateStudentBadRequest() *UpdateStudentBadRequest {
	return &UpdateStudentBadRequest{}
}

/* UpdateStudentBadRequest describes a response with status code 400, with default header values.

Invalid Student ID
*/
type UpdateStudentBadRequest struct {
}

func (o *UpdateStudentBadRequest) Error() string {
	return fmt.Sprintf("[PUT /student][%d] updateStudentBadRequest ", 400)
}

func (o *UpdateStudentBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateStudentNotFound creates a UpdateStudentNotFound with default headers values
func NewUpdateStudentNotFound() *UpdateStudentNotFound {
	return &UpdateStudentNotFound{}
}

/* UpdateStudentNotFound describes a response with status code 404, with default header values.

Student not found
*/
type UpdateStudentNotFound struct {
}

func (o *UpdateStudentNotFound) Error() string {
	return fmt.Sprintf("[PUT /student][%d] updateStudentNotFound ", 404)
}

func (o *UpdateStudentNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateStudentMethodNotAllowed creates a UpdateStudentMethodNotAllowed with default headers values
func NewUpdateStudentMethodNotAllowed() *UpdateStudentMethodNotAllowed {
	return &UpdateStudentMethodNotAllowed{}
}

/* UpdateStudentMethodNotAllowed describes a response with status code 405, with default header values.

Validation exception
*/
type UpdateStudentMethodNotAllowed struct {
}

func (o *UpdateStudentMethodNotAllowed) Error() string {
	return fmt.Sprintf("[PUT /student][%d] updateStudentMethodNotAllowed ", 405)
}

func (o *UpdateStudentMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
