// Code generated by go-swagger; DO NOT EDIT.

package student

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UploadStudentPhotoReader is a Reader for the UploadStudentPhoto structure.
type UploadStudentPhotoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UploadStudentPhotoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUploadStudentPhotoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUploadStudentPhotoOK creates a UploadStudentPhotoOK with default headers values
func NewUploadStudentPhotoOK() *UploadStudentPhotoOK {
	return &UploadStudentPhotoOK{}
}

/* UploadStudentPhotoOK describes a response with status code 200, with default header values.

successful operation
*/
type UploadStudentPhotoOK struct {
}

func (o *UploadStudentPhotoOK) Error() string {
	return fmt.Sprintf("[POST /student/{studentId}/uploadImage][%d] uploadStudentPhotoOK ", 200)
}

func (o *UploadStudentPhotoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
