// Code generated by go-swagger; DO NOT EDIT.

package course

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"example.com/restclient/models"
)

// NewAddCourseParams creates a new AddCourseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddCourseParams() *AddCourseParams {
	return &AddCourseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddCourseParamsWithTimeout creates a new AddCourseParams object
// with the ability to set a timeout on a request.
func NewAddCourseParamsWithTimeout(timeout time.Duration) *AddCourseParams {
	return &AddCourseParams{
		timeout: timeout,
	}
}

// NewAddCourseParamsWithContext creates a new AddCourseParams object
// with the ability to set a context for a request.
func NewAddCourseParamsWithContext(ctx context.Context) *AddCourseParams {
	return &AddCourseParams{
		Context: ctx,
	}
}

// NewAddCourseParamsWithHTTPClient creates a new AddCourseParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddCourseParamsWithHTTPClient(client *http.Client) *AddCourseParams {
	return &AddCourseParams{
		HTTPClient: client,
	}
}

/* AddCourseParams contains all the parameters to send to the API endpoint
   for the add course operation.

   Typically these are written to a http.Request.
*/
type AddCourseParams struct {

	/* Body.

	   Course that needs to be added to ITU
	*/
	Body *models.Course

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add course params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddCourseParams) WithDefaults() *AddCourseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add course params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddCourseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add course params
func (o *AddCourseParams) WithTimeout(timeout time.Duration) *AddCourseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add course params
func (o *AddCourseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add course params
func (o *AddCourseParams) WithContext(ctx context.Context) *AddCourseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add course params
func (o *AddCourseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add course params
func (o *AddCourseParams) WithHTTPClient(client *http.Client) *AddCourseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add course params
func (o *AddCourseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add course params
func (o *AddCourseParams) WithBody(body *models.Course) *AddCourseParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add course params
func (o *AddCourseParams) SetBody(body *models.Course) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddCourseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
