// Code generated by go-swagger; DO NOT EDIT.

package course

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteCourseParams creates a new DeleteCourseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteCourseParams() *DeleteCourseParams {
	return &DeleteCourseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCourseParamsWithTimeout creates a new DeleteCourseParams object
// with the ability to set a timeout on a request.
func NewDeleteCourseParamsWithTimeout(timeout time.Duration) *DeleteCourseParams {
	return &DeleteCourseParams{
		timeout: timeout,
	}
}

// NewDeleteCourseParamsWithContext creates a new DeleteCourseParams object
// with the ability to set a context for a request.
func NewDeleteCourseParamsWithContext(ctx context.Context) *DeleteCourseParams {
	return &DeleteCourseParams{
		Context: ctx,
	}
}

// NewDeleteCourseParamsWithHTTPClient creates a new DeleteCourseParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteCourseParamsWithHTTPClient(client *http.Client) *DeleteCourseParams {
	return &DeleteCourseParams{
		HTTPClient: client,
	}
}

/* DeleteCourseParams contains all the parameters to send to the API endpoint
   for the delete course operation.

   Typically these are written to a http.Request.
*/
type DeleteCourseParams struct {

	/* CourseID.

	   Id of course to delete

	   Format: int64
	*/
	CourseID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete course params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCourseParams) WithDefaults() *DeleteCourseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete course params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCourseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete course params
func (o *DeleteCourseParams) WithTimeout(timeout time.Duration) *DeleteCourseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete course params
func (o *DeleteCourseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete course params
func (o *DeleteCourseParams) WithContext(ctx context.Context) *DeleteCourseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete course params
func (o *DeleteCourseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete course params
func (o *DeleteCourseParams) WithHTTPClient(client *http.Client) *DeleteCourseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete course params
func (o *DeleteCourseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCourseID adds the courseID to the delete course params
func (o *DeleteCourseParams) WithCourseID(courseID int64) *DeleteCourseParams {
	o.SetCourseID(courseID)
	return o
}

// SetCourseID adds the courseId to the delete course params
func (o *DeleteCourseParams) SetCourseID(courseID int64) {
	o.CourseID = courseID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCourseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param courseId
	if err := r.SetPathParam("courseId", swag.FormatInt64(o.CourseID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
