// Code generated by go-swagger; DO NOT EDIT.

package course

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetCourseByIDParams creates a new GetCourseByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCourseByIDParams() *GetCourseByIDParams {
	return &GetCourseByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCourseByIDParamsWithTimeout creates a new GetCourseByIDParams object
// with the ability to set a timeout on a request.
func NewGetCourseByIDParamsWithTimeout(timeout time.Duration) *GetCourseByIDParams {
	return &GetCourseByIDParams{
		timeout: timeout,
	}
}

// NewGetCourseByIDParamsWithContext creates a new GetCourseByIDParams object
// with the ability to set a context for a request.
func NewGetCourseByIDParamsWithContext(ctx context.Context) *GetCourseByIDParams {
	return &GetCourseByIDParams{
		Context: ctx,
	}
}

// NewGetCourseByIDParamsWithHTTPClient creates a new GetCourseByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCourseByIDParamsWithHTTPClient(client *http.Client) *GetCourseByIDParams {
	return &GetCourseByIDParams{
		HTTPClient: client,
	}
}

/* GetCourseByIDParams contains all the parameters to send to the API endpoint
   for the get course by Id operation.

   Typically these are written to a http.Request.
*/
type GetCourseByIDParams struct {

	/* CourseID.

	   ID of course to return

	   Format: int64
	*/
	CourseID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get course by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCourseByIDParams) WithDefaults() *GetCourseByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get course by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCourseByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get course by Id params
func (o *GetCourseByIDParams) WithTimeout(timeout time.Duration) *GetCourseByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get course by Id params
func (o *GetCourseByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get course by Id params
func (o *GetCourseByIDParams) WithContext(ctx context.Context) *GetCourseByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get course by Id params
func (o *GetCourseByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get course by Id params
func (o *GetCourseByIDParams) WithHTTPClient(client *http.Client) *GetCourseByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get course by Id params
func (o *GetCourseByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCourseID adds the courseID to the get course by Id params
func (o *GetCourseByIDParams) WithCourseID(courseID int64) *GetCourseByIDParams {
	o.SetCourseID(courseID)
	return o
}

// SetCourseID adds the courseId to the get course by Id params
func (o *GetCourseByIDParams) SetCourseID(courseID int64) {
	o.CourseID = courseID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCourseByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param courseId
	if err := r.SetPathParam("courseId", swag.FormatInt64(o.CourseID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
