// Code generated by go-swagger; DO NOT EDIT.

package course

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOverviewParams creates a new GetOverviewParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOverviewParams() *GetOverviewParams {
	return &GetOverviewParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOverviewParamsWithTimeout creates a new GetOverviewParams object
// with the ability to set a timeout on a request.
func NewGetOverviewParamsWithTimeout(timeout time.Duration) *GetOverviewParams {
	return &GetOverviewParams{
		timeout: timeout,
	}
}

// NewGetOverviewParamsWithContext creates a new GetOverviewParams object
// with the ability to set a context for a request.
func NewGetOverviewParamsWithContext(ctx context.Context) *GetOverviewParams {
	return &GetOverviewParams{
		Context: ctx,
	}
}

// NewGetOverviewParamsWithHTTPClient creates a new GetOverviewParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOverviewParamsWithHTTPClient(client *http.Client) *GetOverviewParams {
	return &GetOverviewParams{
		HTTPClient: client,
	}
}

/* GetOverviewParams contains all the parameters to send to the API endpoint
   for the get overview operation.

   Typically these are written to a http.Request.
*/
type GetOverviewParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get overview params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOverviewParams) WithDefaults() *GetOverviewParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get overview params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOverviewParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get overview params
func (o *GetOverviewParams) WithTimeout(timeout time.Duration) *GetOverviewParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get overview params
func (o *GetOverviewParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get overview params
func (o *GetOverviewParams) WithContext(ctx context.Context) *GetOverviewParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get overview params
func (o *GetOverviewParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get overview params
func (o *GetOverviewParams) WithHTTPClient(client *http.Client) *GetOverviewParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get overview params
func (o *GetOverviewParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetOverviewParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
