// Code generated by go-swagger; DO NOT EDIT.

package teacher

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteTeacherReader is a Reader for the DeleteTeacher structure.
type DeleteTeacherReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTeacherReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 400:
		result := NewDeleteTeacherBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteTeacherNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteTeacherBadRequest creates a DeleteTeacherBadRequest with default headers values
func NewDeleteTeacherBadRequest() *DeleteTeacherBadRequest {
	return &DeleteTeacherBadRequest{}
}

/* DeleteTeacherBadRequest describes a response with status code 400, with default header values.

Invalid ID supplied
*/
type DeleteTeacherBadRequest struct {
}

func (o *DeleteTeacherBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /teacher/{teacherId}][%d] deleteTeacherBadRequest ", 400)
}

func (o *DeleteTeacherBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteTeacherNotFound creates a DeleteTeacherNotFound with default headers values
func NewDeleteTeacherNotFound() *DeleteTeacherNotFound {
	return &DeleteTeacherNotFound{}
}

/* DeleteTeacherNotFound describes a response with status code 404, with default header values.

Teacher not found
*/
type DeleteTeacherNotFound struct {
}

func (o *DeleteTeacherNotFound) Error() string {
	return fmt.Sprintf("[DELETE /teacher/{teacherId}][%d] deleteTeacherNotFound ", 404)
}

func (o *DeleteTeacherNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
