// Code generated by go-swagger; DO NOT EDIT.

package teacher

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetTeacherByIDParams creates a new GetTeacherByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTeacherByIDParams() *GetTeacherByIDParams {
	return &GetTeacherByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTeacherByIDParamsWithTimeout creates a new GetTeacherByIDParams object
// with the ability to set a timeout on a request.
func NewGetTeacherByIDParamsWithTimeout(timeout time.Duration) *GetTeacherByIDParams {
	return &GetTeacherByIDParams{
		timeout: timeout,
	}
}

// NewGetTeacherByIDParamsWithContext creates a new GetTeacherByIDParams object
// with the ability to set a context for a request.
func NewGetTeacherByIDParamsWithContext(ctx context.Context) *GetTeacherByIDParams {
	return &GetTeacherByIDParams{
		Context: ctx,
	}
}

// NewGetTeacherByIDParamsWithHTTPClient creates a new GetTeacherByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTeacherByIDParamsWithHTTPClient(client *http.Client) *GetTeacherByIDParams {
	return &GetTeacherByIDParams{
		HTTPClient: client,
	}
}

/* GetTeacherByIDParams contains all the parameters to send to the API endpoint
   for the get teacher by Id operation.

   Typically these are written to a http.Request.
*/
type GetTeacherByIDParams struct {

	/* TeacherID.

	   ID of teacher to return

	   Format: int64
	*/
	TeacherID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get teacher by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTeacherByIDParams) WithDefaults() *GetTeacherByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get teacher by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTeacherByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get teacher by Id params
func (o *GetTeacherByIDParams) WithTimeout(timeout time.Duration) *GetTeacherByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get teacher by Id params
func (o *GetTeacherByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get teacher by Id params
func (o *GetTeacherByIDParams) WithContext(ctx context.Context) *GetTeacherByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get teacher by Id params
func (o *GetTeacherByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get teacher by Id params
func (o *GetTeacherByIDParams) WithHTTPClient(client *http.Client) *GetTeacherByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get teacher by Id params
func (o *GetTeacherByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTeacherID adds the teacherID to the get teacher by Id params
func (o *GetTeacherByIDParams) WithTeacherID(teacherID int64) *GetTeacherByIDParams {
	o.SetTeacherID(teacherID)
	return o
}

// SetTeacherID adds the teacherId to the get teacher by Id params
func (o *GetTeacherByIDParams) SetTeacherID(teacherID int64) {
	o.TeacherID = teacherID
}

// WriteToRequest writes these params to a swagger request
func (o *GetTeacherByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param teacherId
	if err := r.SetPathParam("teacherId", swag.FormatInt64(o.TeacherID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
