// Code generated by go-swagger; DO NOT EDIT.

package teacher

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateTeacherReader is a Reader for the UpdateTeacher structure.
type UpdateTeacherReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateTeacherReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateTeacherOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateTeacherBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateTeacherNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewUpdateTeacherMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateTeacherOK creates a UpdateTeacherOK with default headers values
func NewUpdateTeacherOK() *UpdateTeacherOK {
	return &UpdateTeacherOK{}
}

/* UpdateTeacherOK describes a response with status code 200, with default header values.

Success
*/
type UpdateTeacherOK struct {
}

func (o *UpdateTeacherOK) Error() string {
	return fmt.Sprintf("[PUT /teacher][%d] updateTeacherOK ", 200)
}

func (o *UpdateTeacherOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateTeacherBadRequest creates a UpdateTeacherBadRequest with default headers values
func NewUpdateTeacherBadRequest() *UpdateTeacherBadRequest {
	return &UpdateTeacherBadRequest{}
}

/* UpdateTeacherBadRequest describes a response with status code 400, with default header values.

Invalid Teacher ID
*/
type UpdateTeacherBadRequest struct {
}

func (o *UpdateTeacherBadRequest) Error() string {
	return fmt.Sprintf("[PUT /teacher][%d] updateTeacherBadRequest ", 400)
}

func (o *UpdateTeacherBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateTeacherNotFound creates a UpdateTeacherNotFound with default headers values
func NewUpdateTeacherNotFound() *UpdateTeacherNotFound {
	return &UpdateTeacherNotFound{}
}

/* UpdateTeacherNotFound describes a response with status code 404, with default header values.

Teacher not found
*/
type UpdateTeacherNotFound struct {
}

func (o *UpdateTeacherNotFound) Error() string {
	return fmt.Sprintf("[PUT /teacher][%d] updateTeacherNotFound ", 404)
}

func (o *UpdateTeacherNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateTeacherMethodNotAllowed creates a UpdateTeacherMethodNotAllowed with default headers values
func NewUpdateTeacherMethodNotAllowed() *UpdateTeacherMethodNotAllowed {
	return &UpdateTeacherMethodNotAllowed{}
}

/* UpdateTeacherMethodNotAllowed describes a response with status code 405, with default header values.

Validation exception
*/
type UpdateTeacherMethodNotAllowed struct {
}

func (o *UpdateTeacherMethodNotAllowed) Error() string {
	return fmt.Sprintf("[PUT /teacher][%d] updateTeacherMethodNotAllowed ", 405)
}

func (o *UpdateTeacherMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
