// Code generated by go-swagger; DO NOT EDIT.

package teacher

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewUploadTeacherPhotoParams creates a new UploadTeacherPhotoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUploadTeacherPhotoParams() *UploadTeacherPhotoParams {
	return &UploadTeacherPhotoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUploadTeacherPhotoParamsWithTimeout creates a new UploadTeacherPhotoParams object
// with the ability to set a timeout on a request.
func NewUploadTeacherPhotoParamsWithTimeout(timeout time.Duration) *UploadTeacherPhotoParams {
	return &UploadTeacherPhotoParams{
		timeout: timeout,
	}
}

// NewUploadTeacherPhotoParamsWithContext creates a new UploadTeacherPhotoParams object
// with the ability to set a context for a request.
func NewUploadTeacherPhotoParamsWithContext(ctx context.Context) *UploadTeacherPhotoParams {
	return &UploadTeacherPhotoParams{
		Context: ctx,
	}
}

// NewUploadTeacherPhotoParamsWithHTTPClient creates a new UploadTeacherPhotoParams object
// with the ability to set a custom HTTPClient for a request.
func NewUploadTeacherPhotoParamsWithHTTPClient(client *http.Client) *UploadTeacherPhotoParams {
	return &UploadTeacherPhotoParams{
		HTTPClient: client,
	}
}

/* UploadTeacherPhotoParams contains all the parameters to send to the API endpoint
   for the upload teacher photo operation.

   Typically these are written to a http.Request.
*/
type UploadTeacherPhotoParams struct {

	/* AdditionalMetadata.

	   Additional data to pass to server
	*/
	AdditionalMetadata *string

	/* File.

	   file to upload
	*/
	File runtime.NamedReadCloser

	/* TeacherID.

	   ID of teacher to update

	   Format: int64
	*/
	TeacherID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the upload teacher photo params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UploadTeacherPhotoParams) WithDefaults() *UploadTeacherPhotoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the upload teacher photo params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UploadTeacherPhotoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the upload teacher photo params
func (o *UploadTeacherPhotoParams) WithTimeout(timeout time.Duration) *UploadTeacherPhotoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the upload teacher photo params
func (o *UploadTeacherPhotoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the upload teacher photo params
func (o *UploadTeacherPhotoParams) WithContext(ctx context.Context) *UploadTeacherPhotoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the upload teacher photo params
func (o *UploadTeacherPhotoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the upload teacher photo params
func (o *UploadTeacherPhotoParams) WithHTTPClient(client *http.Client) *UploadTeacherPhotoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the upload teacher photo params
func (o *UploadTeacherPhotoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAdditionalMetadata adds the additionalMetadata to the upload teacher photo params
func (o *UploadTeacherPhotoParams) WithAdditionalMetadata(additionalMetadata *string) *UploadTeacherPhotoParams {
	o.SetAdditionalMetadata(additionalMetadata)
	return o
}

// SetAdditionalMetadata adds the additionalMetadata to the upload teacher photo params
func (o *UploadTeacherPhotoParams) SetAdditionalMetadata(additionalMetadata *string) {
	o.AdditionalMetadata = additionalMetadata
}

// WithFile adds the file to the upload teacher photo params
func (o *UploadTeacherPhotoParams) WithFile(file runtime.NamedReadCloser) *UploadTeacherPhotoParams {
	o.SetFile(file)
	return o
}

// SetFile adds the file to the upload teacher photo params
func (o *UploadTeacherPhotoParams) SetFile(file runtime.NamedReadCloser) {
	o.File = file
}

// WithTeacherID adds the teacherID to the upload teacher photo params
func (o *UploadTeacherPhotoParams) WithTeacherID(teacherID int64) *UploadTeacherPhotoParams {
	o.SetTeacherID(teacherID)
	return o
}

// SetTeacherID adds the teacherId to the upload teacher photo params
func (o *UploadTeacherPhotoParams) SetTeacherID(teacherID int64) {
	o.TeacherID = teacherID
}

// WriteToRequest writes these params to a swagger request
func (o *UploadTeacherPhotoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AdditionalMetadata != nil {

		// form param additionalMetadata
		var frAdditionalMetadata string
		if o.AdditionalMetadata != nil {
			frAdditionalMetadata = *o.AdditionalMetadata
		}
		fAdditionalMetadata := frAdditionalMetadata
		if fAdditionalMetadata != "" {
			if err := r.SetFormParam("additionalMetadata", fAdditionalMetadata); err != nil {
				return err
			}
		}
	}

	if o.File != nil {

		if o.File != nil {
			// form file param file
			if err := r.SetFileParam("file", o.File); err != nil {
				return err
			}
		}
	}

	// path param teacherId
	if err := r.SetPathParam("teacherId", swag.FormatInt64(o.TeacherID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
